spring.application.name=ConfigService

server.port=8888

#spring.cloud.config.server.native.search-locations=classpath:/config



eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
spring.cloud.config.server.git.uri=https://gitlab1.rpsconsulting.in/26SUB0734_U20/wipro-config-repo.git
spring.cloud.config.server.git.username=26SUB0734_U20@rpsconsulting.in
spring.cloud.config.server.git.password=Wipro@2026
spring.cloud.config.server.git.skip-ssl-validation=true
spring.cloud.config.server.git.default-label=main
spring.cloud.config.server.git.clone-on-start=true